services:
  stt-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stt-service
    ports:
      - "9001:9000"
    environment:
      TRANSCRIBE_DEVICE: cuda
      WHISPER_MODEL_SIZE: large-v3
      HF_TOKEN: ${HF_TOKEN:-}
      ENABLE_DIARIZATION: "true"
    volumes:
      - ./cache/hf:/root/.cache/huggingface
      - ./cache/pyannote:/root/.cache/pyannote
      - ./cache/whisper:/root/.cache/whisper
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

