services:
  stt-server:
    build:
      context: .
      args:
        HF_TOKEN: ${HF_TOKEN}
        ASR_MODEL: ${ASR_MODEL}
        DIARIZATION_MODEL: ${DIARIZATION_MODEL}
    container_name: stt-server
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./app:/app
