version: '3.8'

services:
  server:
    container_name: whisper-diarization-server
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./pip-cache:/root/.cache/pip
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all  # Use all available GPUs, or specify 2
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    stdin_open: true
    tty: true
