services:
  stt-server:
    build: 
      context: .
      args:
        - ASR_MODEL=${ASR_MODEL:-base}
        - DIARIZATION_MODEL=${DIARIZATION_MODEL:-pyannote/speaker-diarization-3.1}
        - HF_TOKEN=${HF_TOKEN}
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - ASR_MODEL=${ASR_MODEL:-base}
      - DIARIZATION_MODEL=${DIARIZATION_MODEL:-pyannote/speaker-diarization-3.1}
      - HF_TOKEN=${HF_TOKEN}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
