services:
  stt-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whisper-stt-server
    ports:
      - "9001:9000" # API accessible at http://localhost:9001
    environment:
      - HF_TOKEN= # Replace with your Hugging Face token
    volumes:
      - ./cache:/root/.cache # Persists model cache
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
